GRANT ALL PRIVILEGES ON DATABASE opendata TO contributor;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO contributor;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO contributor;